# Generated by Django 5.0.2 on 2024-11-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_hotelbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(blank=True, max_length=16)),
                ('Expiry_Date', models.DateField()),
                ('Card_Name', models.TextField(blank=True)),
                ('security_code', models.CharField(blank=True, max_length=3)),
            ],
        ),
    ]
