# Generated by Django 5.0.2 on 2024-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='Expiry_Date',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
