# Generated by Django 5.0.2 on 2024-11-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_paymentmodel_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='Card_Name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
